use crate::ast::*;
/// Transpiles a Wlel program to C99 source.
pub fn gen_program(p: &Program) -> String {
    let mut out = String::new();
    out.push_str("/* generated by wlel */\n");
    out.push_str("#include <stdio.h>\n#include <string.h>\n\n");
    // runtime builtins
    out.push_str("static void wlel_print_int(long long v) { printf(\"%lld\\n\", v); }\n");
    out.push_str("static void wlel_print_str(const char* s) { fputs(s, stdout); }\n\n");

    // prototypes so forward references link correctly
    for f in &p.funcs {
        if f.name == "main" {
            continue;
        }
        let ret = c_type(f.ret_type.as_deref().unwrap_or("void"));
        let params: Vec<String> = f
            .params
            .iter()
            .map(|pa| format!("{} {}", c_type(pa.ty.as_deref().unwrap_or("int")), pa.name))
            .collect();
        out.push_str(&format!(
            "static {} {}({});\n",
            ret,
            f.name,
            params.join(", ")
        ));
    }
    out.push('\n');

    for f in &p.funcs {
        let ret = f.ret_type.as_deref().unwrap_or("void");
        let ret_c = c_type(ret);
        let params: Vec<String> = f
            .params
            .iter()
            .map(|pa| format!("{} {}", c_type(pa.ty.as_deref().unwrap_or("int")), pa.name))
            .collect();
        if f.name == "main" {
            out.push_str(&format!("int main(void) {{\n"));
        } else {
            out.push_str(&format!("{} {}({}) {{\n", ret_c, f.name, params.join(", ")));
        }
        gen_block(&f.body, 1, &mut out);
        out.push_str("}\n\n");
    }
    out
}

fn c_type(t: &str) -> &'static str {
    match t {
        "int" | "void" => if t == "int" { "long long" } else { "void" },
        "float" => "double",
        "bool" => "_Bool",
        "string" => "const char*",
        _ => "long long",
    }
}

fn indent(level: usize, out: &mut String) {
    for _ in 0..level {
        out.push_str("    ");
    }
}

fn gen_block(b: &Block, level: usize, out: &mut String) {
    for s in &b.0 {
        gen_stmt(s, level, out);
    }
}

fn gen_stmt(s: &Stmt, level: usize, out: &mut String) {
    match s {
        Stmt::Let(name, ty_ann, e) => {
            indent(level, out);
            let cty = match ty_ann.as_deref().map(c_type) {
                Some(t) => t.to_string(),
                None => infer_cty(e).to_string(),
            };
            out.push_str(&format!("{} {} = {};\n", cty, name, gen_expr(e)));
        }
        Stmt::Assign(name, e) => {
            indent(level, out);
            out.push_str(&format!("{} = {};\n", name, gen_expr(e)));
        }
        Stmt::If(i) => gen_if(i, level, out),
        Stmt::While(cond, body) => {
            indent(level, out);
            out.push_str(&format!("while ({}) {{\n", gen_expr(cond)));
            gen_block(body, level + 1, out);
            indent(level, out);
            out.push_str("}\n");
        }
        Stmt::Return(Some(e)) => {
            indent(level, out);
            out.push_str(&format!("return {};\n", gen_expr(e)));
        }
        Stmt::Return(None) => {
            indent(level, out);
            out.push_str("return;\n");
        }
        Stmt::ExprStmt(e) => {
            indent(level, out);
            out.push_str(&format!("{};\n", gen_expr(e)));
        }
    }
}

fn gen_if(i: &IfStmt, level: usize, out: &mut String) {
    indent(level, out);
    out.push_str(&format!("if ({}) {{\n", gen_expr(&i.cond)));
    gen_block(&i.then_body, level + 1, out);
    match &i.else_branch {
        None => {
            indent(level, out);
            out.push_str("}\n");
        }
        Some(ElseBranch::Block(els)) => {
            indent(level, out);
            out.push_str("} else {\n");
            gen_block(els, level + 1, out);
            indent(level, out);
            out.push_str("}\n");
        }
        Some(ElseBranch::If(inner)) => {
            indent(level, out);
            out.push_str("} else ");
            gen_if(inner, level, out);
        }
    }
}

fn gen_expr(e: &Expr) -> String {
    match e {
        Expr::Int(v) => v.to_string(),
        Expr::Float(v) => format!("{v:?}"),
        Expr::Str(s) => c_string_literal(s),
        Expr::Bool(true) => "1".into(),
        Expr::Bool(false) => "0".into(),
        Expr::Ident(n) => n.clone(),
        Expr::Unary(UnOp::Neg, x) => format!("(-{})", gen_expr(x)),
        Expr::Unary(UnOp::Not, x) => format!("(!{})", gen_expr(x)),
        Expr::Binary(op, l, r) => format!(
            "({} {} {})",
            gen_expr(l),
            binop_str(*op),
            gen_expr(r)
        ),
        Expr::Call(f, args) => {
            let a: Vec<String> = args.iter().map(gen_expr).collect();
            format!("{}({})", f, a.join(", "))
        }
    }
}

fn binop_str(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
        BinOp::Eq => "==",
        BinOp::Ne => "!=",
        BinOp::Lt => "<",
        BinOp::Gt => ">",
        BinOp::Le => "<=",
        BinOp::Ge => ">=",
        BinOp::And => "&&",
        BinOp::Or => "||",
    }
}

/// fallback when the checker did not annotate (direct gen without check)
fn infer_cty(e: &Expr) -> &'static str {
    match e {
        Expr::Float(_) => "double",
        Expr::Str(_) => "const char*",
        Expr::Bool(_) => "_Bool",
        _ => "long long",
    }
}

fn c_string_literal(s: &str) -> String {
    let mut out = String::from("\"");
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\0' => out.push_str("\\0"),
            other => out.push(other),
        }
    }
    out.push('"');
    out
}
