use crate::ast::*;

/// Transpiles a Wlel program to C99 source.
pub fn gen_program(p: &Program) -> String {
    let mut cg = Cg {
        out: String::new(),
        defers: Vec::new(),
    };
    gen_program_into(&mut cg, p);
    cg.out
}

struct Cg {
    out: String,
    /// defers registered by enclosing blocks, in registration order
    defers: Vec<Expr>,
}

fn gen_program_into(cg: &mut Cg, p: &Program) {
    cg.out.push_str("/* generated by wlel */\n");
    cg.out.push_str("#include <stdio.h>\n#include <string.h>\n\n");
    // runtime builtins
    cg.out.push_str("static void wlel_print_int(long long v) { printf(\"%lld\\n\", v); }\n");
    cg.out.push_str("static void wlel_print_float(double v) { printf(\"%g\\n\", v); }\n");
    cg.out.push_str("static void wlel_print_str(const char* s) { fputs(s, stdout); }\n\n");
    cg.out.push_str("#include <stdlib.h>\n\n");
    cg.out.push_str("static void std__print_int(long long v) { printf(\"%lld\", v); }\n");
    cg.out.push_str("static void std__print_float(double v) { printf(\"%g\", v); }\n");
    cg.out.push_str("static void std__print_str(const char* s) { fputs(s, stdout); }\n");
    cg.out.push_str("static void std__println_int(long long v) { printf(\"%lld\\n\", v); }\n");
    cg.out.push_str("static void std__println_float(double v) { printf(\"%g\\n\", v); }\n");
    cg.out.push_str("static void std__println_str(const char* s) { printf(\"%s\\n\", s); }\n");
    cg.out.push_str("static _Bool std__streq(const char* a, const char* b) { return strcmp(a, b) == 0; }\n");
    cg.out.push_str("static long long std__abs(long long v) { return v < 0 ? -v : v; }\n");
    cg.out.push_str("static long long std__min(long long a, long long b) { return a < b ? a : b; }\n");
    cg.out.push_str("static long long std__max(long long a, long long b) { return a > b ? a : b; }\n\n");
    cg.out.push_str("typedef struct WArena { unsigned char* buf; unsigned long long cap; unsigned long long used; struct WArena* next; } WArena;\n");
    cg.out.push_str("static void* wlel_alloc(unsigned long long n) { return malloc(n); }\n");
    cg.out.push_str("static void wlel_free(void* p) { free(p); }\n");
    cg.out.push_str("static WArena* wlel_arena_new(unsigned long long cap) {\n");
    cg.out.push_str("    WArena* a = (WArena*)malloc(sizeof(WArena));\n");
    cg.out.push_str("    a->buf = (unsigned char*)malloc(cap ? cap : 1);\n");
    cg.out.push_str("    a->cap = cap ? cap : 1; a->used = 0; a->next = 0;\n");
    cg.out.push_str("    return a;\n");
    cg.out.push_str("}\n");
    cg.out.push_str("static void* wlel_arena_alloc(WArena* a, unsigned long long n) {\n");
    cg.out.push_str("    if (a->used + n <= a->cap) { void* p = a->buf + a->used; a->used += n; return p; }\n");
    cg.out.push_str("    WArena* chunk = (WArena*)malloc(sizeof(WArena));\n");
    cg.out.push_str("    unsigned long long cap = n > a->cap ? n : a->cap;\n");
    cg.out.push_str("    chunk->buf = (unsigned char*)malloc(cap); chunk->cap = cap; chunk->used = n; chunk->next = a->next;\n");
    cg.out.push_str("    a->next = chunk;\n");
    cg.out.push_str("    return chunk->buf;\n");
    cg.out.push_str("}\n");
    cg.out.push_str("static void wlel_arena_free(WArena* a) {\n");
    cg.out.push_str("    while (a) { WArena* nx = a->next; free(a->buf); free(a); a = nx; }\n");
    cg.out.push_str("}\n\n");

    // struct typedefs
    for st in &p.structs {
        cg.out.push_str("typedef struct {\n");
        for (fname, fty) in &st.fields {
            cg.out.push_str(&format!("    {} {};\n", c_type(fty), fname));
        }
        cg.out.push_str(&format!("}} {};\n\n", st.name));
    }

    // prototypes so forward references link correctly
    for f in &p.funcs {
        if f.name == "main" {
            continue;
        }
        let ret = c_type(f.ret_type.as_deref().unwrap_or("void"));
        let params: Vec<String> = f
            .params
            .iter()
            .map(|pa| format!("{} {}", c_type(pa.ty.as_deref().unwrap_or("int")), pa.name))
            .collect();
        cg.out.push_str(&format!(
            "static {} {}({});\n",
            ret,
            f.name,
            params.join(", ")
        ));
    }
    cg.out.push('\n');

    for f in &p.funcs {
        let ret_c = c_type(f.ret_type.as_deref().unwrap_or("void"));
        let params: Vec<String> = f
            .params
            .iter()
            .map(|pa| format!("{} {}", c_type(pa.ty.as_deref().unwrap_or("int")), pa.name))
            .collect();
        if f.name == "main" {
            cg.out.push_str("int main(void) {\n");
        } else {
            cg.out.push_str(&format!("{} {}({}) {{\n", ret_c, f.name, params.join(", ")));
        }
        gen_block(cg, &f.body, 1);
        cg.out.push_str("}\n\n");
    }
}

fn indent(out: &mut String, level: usize) {
    for _ in 0..level {
        out.push_str("    ");
    }
}

fn gen_block(cg: &mut Cg, b: &Block, level: usize) {
    let base = cg.defers.len();
    for s in &b.0 {
        gen_stmt(cg, s, level);
    }
    // scope exit: run this block's defers in reverse (LIFO)
    while cg.defers.len() > base {
        let d = cg.defers.pop().unwrap();
        indent(&mut cg.out, level);
        cg.out.push_str(&format!("{};\n", gen_expr(&d)));
    }
}

fn gen_stmt(cg: &mut Cg, s: &Stmt, level: usize) {
    match s {
        Stmt::Let(name, ty_ann, e) => {
            indent(&mut cg.out, level);
            let decl = match ty_ann.as_deref() {
                Some(t) => c_decl(t, name),
                None => format!("{} {}", infer_cty(e), name),
            };
            cg.out
                .push_str(&format!("{} = {};\n", decl, gen_expr(e)));
        }
        Stmt::Assign(a) => {
            indent(&mut cg.out, level);
            cg.out.push_str(&format!(
                "{} = {};\n",
                gen_expr(&a.target),
                gen_expr(&a.value)
            ));
        }
        Stmt::If(i) => gen_if(cg, i, level),
        Stmt::While(cond, body) => {
            indent(&mut cg.out, level);
            cg.out.push_str(&format!("while ({}) {{\n", gen_expr(cond)));
            gen_block(cg, body, level + 1);
            indent(&mut cg.out, level);
            cg.out.push_str("}\n");
        }
        Stmt::Return(e) => {
            indent(&mut cg.out, level);
            // a `return` exits the whole function, so every defer registered
            // by this block and its enclosing blocks runs first (LIFO)
            if !cg.defers.is_empty() {
                cg.out.push_str("{ ");
                for d in &cg.defers {
                    cg.out.push_str(&format!("{}; ", gen_expr(d)));
                }
            }
            match e {
                Some(e) => cg.out.push_str(&format!("return {};", gen_expr(e))),
                None => cg.out.push_str("return;"),
            }
            if !cg.defers.is_empty() {
                cg.out.push_str(" }");
            }
            cg.out.push('\n');
        }
        Stmt::ExprStmt(e) => {
            indent(&mut cg.out, level);
            cg.out.push_str(&format!("{};\n", gen_expr(e)));
        }
        Stmt::Block(b) => {
            indent(&mut cg.out, level);
            cg.out.push_str("{\n");
            gen_block(cg, b, level + 1);
            indent(&mut cg.out, level);
            cg.out.push_str("}\n");
        }
        Stmt::Defer(e) => {
            cg.defers.push(e.clone());
        }
    }
}

fn gen_if(cg: &mut Cg, i: &IfStmt, level: usize) {
    indent(&mut cg.out, level);
    cg.out.push_str(&format!("if ({}) {{\n", gen_expr(&i.cond)));
    gen_block(cg, &i.then_body, level + 1);
    match &i.else_branch {
        None => {
            indent(&mut cg.out, level);
            cg.out.push_str("}\n");
        }
        Some(ElseBranch::Block(els)) => {
            indent(&mut cg.out, level);
            cg.out.push_str("} else {\n");
            gen_block(cg, els, level + 1);
            indent(&mut cg.out, level);
            cg.out.push_str("}\n");
        }
        Some(ElseBranch::If(inner)) => {
            indent(&mut cg.out, level);
            cg.out.push_str("} else ");
            gen_if(cg, inner, level);
        }
    }
}

fn gen_expr(e: &Expr) -> String {
    match e {
        Expr::Int(v) => v.to_string(),
        Expr::Float(v) => format!("{v:?}"),
        Expr::Str(s) => c_string_literal(s),
        Expr::Bool(true) => "1".into(),
        Expr::Bool(false) => "0".into(),
        Expr::Ident(n) => n.clone(),
        Expr::Unary(UnOp::Neg, x) => format!("(-{})", gen_expr(x)),
        Expr::Unary(UnOp::Not, x) => format!("(!{})", gen_expr(x)),
        Expr::Binary(op, l, r) => {
            format!("({} {} {})", gen_expr(l), binop_str(*op), gen_expr(r))
        }
        Expr::Call(f, args) => {
            if f == "std::len" {
                let arr = gen_expr(&args[0]);
                return format!("((long long)(sizeof({}) / sizeof(({}[0]))))", arr, arr);
            }
            let a: Vec<String> = args.iter().map(gen_expr).collect();
            format!("{}({})", f.replace("::", "__"), a.join(", "))
        }
        Expr::Sizeof(ty) => format!("sizeof({})", c_sizeof_ty(ty)),
        Expr::Cast(ty, x) => format!("({})({})", c_type(ty), gen_expr(x)),
        Expr::Index(b, i) => format!("{}[{}]", gen_expr(b), gen_expr(i)),
        Expr::ArrayLit(elems) => {
            let parts: Vec<String> = elems.iter().map(gen_expr).collect();
            format!("{{ {} }}", parts.join(", "))
        }
        Expr::AddrOf(x) => format!("&{}", gen_expr(x)),
        Expr::Deref(x) => format!("(*{})", gen_expr(x)),
        Expr::Field(obj, f) => format!("{}.{}", gen_expr(obj), f),
        Expr::StructLit(name, fields) => {
            let parts: Vec<String> = fields
                .iter()
                .map(|(n, v)| format!(".{} = {}", n, gen_expr(v)))
                .collect();
            format!("({}){{ {} }}", name, parts.join(", "))
        }
    }
}

fn binop_str(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
        BinOp::Eq => "==",
        BinOp::Ne => "!=",
        BinOp::Lt => "<",
        BinOp::Gt => ">",
        BinOp::Le => "<=",
        BinOp::Ge => ">=",
        BinOp::And => "&&",
        BinOp::Or => "||",
    }
}

/// exact C type for a resolved Wlel type string ("int", "*Pt", ...)
fn c_type(t: &str) -> String {
    let stars = t.chars().take_while(|c| *c == '*').count();
    let base = &t[stars..];
    let base_c = match base {
        "int" => "long long",
        "float" => "double",
        "bool" => "_Bool",
        "string" => "const char*",
        "void" => "void",
        other => other, // struct name
    };
    format!("{}{}", base_c, "*".repeat(stars))
}

/// type inside sizeof(): arrays keep their length (`long long[5]`)
fn c_sizeof_ty(ty: &str) -> String {
    if let Some(rest) = ty.strip_prefix('[') {
        let close = rest.rfind(']').unwrap_or(rest.len());
        let inner = &rest[..close];
        if let Some((base, n)) = inner.rsplit_once(';') {
            return format!("{}[{}]", c_type(base.trim()), n.trim());
        }
    }
    c_type(ty)
}

/// declaration fragment: arrays need `long long a[4]`, others `long long a`
fn c_decl(ty: &str, name: &str) -> String {
    if let Some(rest) = ty.strip_prefix('[') {
        let close = rest.rfind(']').unwrap_or(rest.len());
        let inner = &rest[..close];
        if let Some((base, n)) = inner.rsplit_once(';') {
            let bt = c_type(base.trim());
            let stars = bt.chars().take_while(|c| *c == '*').count();
            return format!("{}{} {}[{}]", &bt[stars..], "*".repeat(stars), name, n.trim());
        }
    }
    format!("{} {}", c_type(ty), name)
}

/// fallback when the checker did not annotate (direct gen without check)
fn infer_cty(e: &Expr) -> &'static str {
    match e {
        Expr::Float(_) => "double",
        Expr::Str(_) => "const char*",
        Expr::Bool(_) => "_Bool",
        _ => "long long",
    }
}

fn c_string_literal(s: &str) -> String {
    let mut out = String::from("\"");
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\0' => out.push_str("\\0"),
            other => out.push(other),
        }
    }
    out.push('"');
    out
}
